// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './comic-neue.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };

const bundle = {
  version: 0,
  family: 'Comic Neue',
  lineCap: 'round',
  fontUrl,
  fontFaceCSS: `@font-face { font-family: 'Comic Neue'; src: url(${fontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 900,
  descender: -250,
  glyphData,
} as const;

export default bundle;
